name: admin_dashboard
description: A new Flutter project.

publish_to: 'none'

version: 0.5.0+1

environment:
  sdk: '>=2.17.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  ##***********************************************************
  ##                       Basic
  ##***********************************************************
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  get: ^4.6.1
#  flutter_reorderable_list: ^1.2.0
  get_storage: ^2.0.3
  #  flutter_local_notifications: ^9.0.2
  logger: ^1.1.0
  path_provider:
  path:
  intl: ^0.17.0
  dio: ^4.0.4
  json_annotation: ^4.6.0
  cached_network_image: ^3.2.0
#  internet_connection_checker: ^0.0.1+3
  connectivity_plus: ^2.3.0
#  gradient_borders: ^0.2.0
  flutter_screenutil: ^5.3.1 #for responsive
  file_picker: ^4.5.1
#  build_runner: ^2.2.0
  collection:
  json_serializable: ^6.3.1

  ##***********************************************************
  ##                       UI Base
  ##***********************************************************
#  cupertino_icons: ^1.0.4
#  fl_chart: ^0.55.0
  ##***********************************************************
  ##                       This Project
  ##***********************************************************
  flutter_svg: ^1.0.3
#  google_fonts: ^3.0.1
  flutter_rating_bar: ^4.0.1
  carousel_slider: ^4.1.1
  pin_code_fields: ^7.4.0
  alt_sms_autofill: ^1.0.0
#  flutter_osm_plugin: ^0.39.1
  flutter_map: ^3.0.0
#  permission_handler: ^10.0.0
  location: ^4.4.0
#  scroll_snap_list: ^0.9.1
  lottie: ^1.4.2
  share_plus: ^4.5.2
  smooth_page_indicator: ^1.0.0+2
  currency_text_input_formatter: ^2.1.8
  flutter_slidable:
    path: edit_packages/flutter_slidable-2.0.0
  persian_datetime_picker:
    path: edit_packages/persian-datetime-picker
  pandabar:
    path: edit_packages/pandabar-0.1.2
  countdown:
    path: edit_packages/countdown-0.1.0
  badges: ^2.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: b-nazanin
      fonts:
        - asset: fonts/b_nazanin.TTF
    - family: vazir
      fonts:
        - asset: fonts/Vazir-Bold.ttf
          weight : 700
        - asset: fonts/Vazir-Regular.ttf
          weight : 500